@url_dev=http://localhost:3056/v1/api


### signup

POST {{url_dev}}/shop/signup 
Content-Type: application/json
x-api-key: c73c278aa9c604a0be0ec5c6d38c0a6d41f1d2f83394fb5e8ee6ea16dabb72a764ed9be06ae9c1d85e3f8a0f98c9faf0f3705f6c909319c8d1b99721ad1c7ba4

{
    "name":"Shop TIPS",
    "email":"shoptipjs@gmail.com",
    "password":"abc123"
}